language: php

sudo: false

matrix:
    include:
        - php: 5.6

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - composer self-update

install:
    - composer install

before_script:
    - phpenv rehash

script:
    - vendor/bin/phpcs -n --standard=PSR2 --extensions=php --ignore=vendor/* *
