#!/usr/bin/env php
<?php

$autoloaders = [__DIR__ . '/../../../autoload.php', __DIR__ . '/../vendor/autoload.php'];

foreach ($autoloaders as $autoloader) {
    if (is_file($autoloader)) {
        require_once $autoloader;
        break;
    }
}

$deployer = new Enrise\TravisDeployer\TravisDeployer();
$deployer->deploy();
